### ISSUE TITLE
PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by epicure** [openai/shap-e#2]
sample_text_to_3d.ipynb does not work with the current Colab. 

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/422362/236366740-7c283767-1479-42e4-b94f-e126fa826e30.png">

Colab: https://colab.research.google.com/drive/1OFzAnSE2_qMARTnu3TV9Bj_scqhvKsIO?usp=sharing

**Comment by jiaoyining** [comment]
I have same problem.

**Comment by unixpickle** [comment]
This is likely the result of the local model weights being corrupted or not completely downloaded. Not sure how this happened in your cases, but it could be the result of multiple instances / notebooks downloading the same file at once.

I've pushed a change to the repository to verify checksums of downloaded model weights, so that you can check if this is what's happening. If this is the case, it should give a helpful error message indicating that you should delete the corrupted file.

**Comment by epicure** [comment]
Now it's working. Thank you!
<img width="792" alt="image" src="https://user-images.githubusercontent.com/422362/236590657-52d9e065-f18b-4275-b6b7-f2635921da57.png">
